# SPDX-License-Identifier: BSD-3-Clause
# Assert the intended CLI failure, retaining signal/loader failures as failures.
cmake_minimum_required(VERSION 3.24)
foreach(_required TOOL_EXECUTABLE EXPECTED_EXIT_CODE EXPECTED_DIAGNOSTICS)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "Missing negative-test input: ${_required}")
  endif()
endforeach()
if(NOT EXPECTED_EXIT_CODE MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "Expected exit code must be a nonzero integer")
endif()
execute_process(COMMAND "${TOOL_EXECUTABLE}" ${TOOL_ARGUMENTS}
  RESULT_VARIABLE _status OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr TIMEOUT 30)
if(NOT "${_status}" STREQUAL "${EXPECTED_EXIT_CODE}")
  message(FATAL_ERROR "Expected tool exit ${EXPECTED_EXIT_CODE}; got '${_status}'.\n${_stdout}\n${_stderr}")
endif()
set(_output "${_stdout}\n${_stderr}")
if(_output MATCHES "dyld\\[|Library not loaded:|Symbol not found:|error while loading shared libraries:|symbol lookup error:|Segmentation fault|Subprocess aborted")
  message(FATAL_ERROR "Tool failed in the runtime loader or crashed:\n${_output}")
endif()
foreach(_diagnostic IN LISTS EXPECTED_DIAGNOSTICS)
  string(FIND "${_output}" "${_diagnostic}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "Tool failed for the wrong reason: missing '${_diagnostic}'.\n${_output}")
  endif()
endforeach()
message(STATUS "Expected tool exit and diagnostics verified")
