# SPDX-License-Identifier: BSD-3-Clause
# A package consumes installed, immutable SDKs; the suite never adds core sources.
# Canonical source: OpenMS4-tests/cmake; sync copies with tools/sync_build_helpers.py.
include_guard(GLOBAL)
option(OPENMS4_REQUIRE_CLEAN_SOURCE "Reject uncommitted package sources in published builds" OFF)
function(openms4_find_package name)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  file(READ "${_lock_file}" _lock)
  string(JSON _version ERROR_VARIABLE _err GET "${_lock}" dependencies "${name}" version)
  if(_err)
    message(FATAL_ERROR "No dependency lock for ${name}: ${_err}")
  endif()
  string(JSON _revision GET "${_lock}" dependencies "${name}" source_revision)
  if(NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "${name} source pin is not resolved")
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40)
    message(FATAL_ERROR "${name} requires a full 40-character Git revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(${name} ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT "${${name}_SOURCE_REVISION}" STREQUAL "${_revision}")
    message(FATAL_ERROR "${name} SDK revision mismatch: expected ${_revision}, got ${${name}_SOURCE_REVISION}")
  endif()
  if(OPENMS4_REQUIRE_CLEAN_SOURCE AND ${name}_SOURCE_DIRTY)
    message(FATAL_ERROR "${name} SDK was built from uncommitted sources")
  endif()
  # Propagate SDK metadata; imported targets already belong to this directory.
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^${name}_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_find_core)
  openms4_find_package(OpenMS ${ARGN})
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_source_revision output)
  # Child project() calls must not change the owning package identity.
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    get_filename_component(_package_root "${OPENMS4_DEPENDENCY_LOCK_FILE}" DIRECTORY)
  else()
    set(_package_root "${PROJECT_SOURCE_DIR}")
  endif()
  if(EXISTS "${_package_root}/.git")
    find_package(Git REQUIRED)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
      WORKING_DIRECTORY "${_package_root}"
      OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine package Git revision; set OPENMS4_SOURCE_REVISION explicitly")
    endif()
    if(OPENMS4_SOURCE_REVISION AND NOT OPENMS4_SOURCE_REVISION STREQUAL _revision)
      message(FATAL_ERROR "Source revision override differs from the package Git HEAD")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=all
      WORKING_DIRECTORY "${_package_root}" OUTPUT_VARIABLE _changes RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine uncommitted source changes")
    endif()
    set(_dirty FALSE)
    if(NOT _changes STREQUAL "")
      set(_dirty TRUE)
    endif()
  else()
    if(NOT OPENMS4_SOURCE_REVISION OR NOT DEFINED OPENMS4_SOURCE_DIRTY)
      message(FATAL_ERROR "Source archives must set OPENMS4_SOURCE_REVISION and OPENMS4_SOURCE_DIRTY explicitly")
    endif()
    set(_revision "${OPENMS4_SOURCE_REVISION}")
    set(_dirty "${OPENMS4_SOURCE_DIRTY}")
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OPENMS4_SOURCE_REVISION must be the full 40-character lowercase package commit")
  endif()
  if(OPENMS4_REQUIRE_CLEAN_SOURCE AND _dirty)
    message(FATAL_ERROR "Published packages require clean sources")
  endif()
  set(${output} "${_revision}" PARENT_SCOPE)
  if(ARGC GREATER 1)
    set(${ARGV1} "${_dirty}" PARENT_SCOPE)
  endif()
endfunction()

# Find only immutable data/feature metadata; suitable for LANGUAGES NONE projects.
function(openms4_find_core_data)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  file(READ "${_lock_file}" _lock)
  string(JSON _version GET "${_lock}" dependencies OpenMS version)
  string(JSON _revision GET "${_lock}" dependencies OpenMS source_revision)
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OpenMS requires a resolved 40-character source revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(OpenMSData ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT OpenMSData_SOURCE_REVISION STREQUAL _revision)
    message(FATAL_ERROR "OpenMS data revision mismatch: expected ${_revision}, got ${OpenMSData_SOURCE_REVISION}")
  endif()
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

# A combined install prefix is the default deployment layout. Separately installed
# SDKs may be supplied explicitly through CMAKE_INSTALL_RPATH; no producer path leaks.
function(openms4_install_rpath target)
  if(UNIX)
    get_target_property(_type ${target} TYPE)
    get_target_property(_bundle ${target} MACOSX_BUNDLE)
    if(_bundle)
      set(_directory "${CMAKE_INSTALL_BINDIR}/${target}.app/Contents/MacOS")
    elseif(_type STREQUAL "EXECUTABLE")
      set(_directory "${CMAKE_INSTALL_BINDIR}")
    else()
      set(_directory "${CMAKE_INSTALL_LIBDIR}")
    endif()
    file(RELATIVE_PATH _relative "/${_directory}" "/${CMAKE_INSTALL_LIBDIR}")
    if(APPLE)
      set(_origin "@loader_path")
    else()
      set(_origin "$ORIGIN")
    endif()
    set_target_properties(${target} PROPERTIES
      INSTALL_RPATH "${_origin}/${_relative};${CMAKE_INSTALL_RPATH}"
      INSTALL_RPATH_USE_LINK_PATH FALSE)
  endif()
endfunction()
